import type { Patient, Claim, Appointment, ActivityItem, Staff, Ticket, Policy, FraudAlert } from '../types'

export const demoPatients: Patient[] = [
  {
    id: 'pat-001',
    name: 'Rajesh Kumar',
    age: 58,
    gender: 'Male',
    phone: '+91 98765 43210',
    email: 'rajesh.kumar@email.com',
    address: '42, Lajpat Nagar',
    city: 'New Delhi',
    state: 'Delhi',
    insuranceType: 'Star Health Insurance',
    insuranceId: 'SHI-2025-789456',
    conditions: ['Type 2 Diabetes', 'Hypertension'],
    medications: ['Metformin 500mg', 'Amlodipine 5mg', 'Atorvastatin 10mg'],
    allergies: ['Penicillin'],
    bloodGroup: 'O+',
    lastVisit: '2026-03-25',
    nextAppointment: '2026-04-02',
    riskScore: 62,
    satisfactionScore: 88,
    vitals: { bp: '128/82', heartRate: 72, spO2: 98, bloodGlucose: 118, temperature: 36.6, weight: 78 },
  },
  {
    id: 'pat-002',
    name: 'Priya Mehta',
    age: 34,
    gender: 'Female',
    phone: '+91 87654 32109',
    email: 'priya.mehta@email.com',
    address: '15, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    insuranceType: 'HDFC ERGO',
    insuranceId: 'HDE-2026-112233',
    conditions: ['Asthma'],
    medications: ['Salbutamol Inhaler'],
    allergies: [],
    bloodGroup: 'A+',
    lastVisit: '2026-03-27',
    nextAppointment: '2026-04-05',
    riskScore: 28,
    satisfactionScore: 95,
    vitals: { bp: '118/76', heartRate: 68, spO2: 97, bloodGlucose: 92, temperature: 36.4, weight: 62 },
  },
  {
    id: 'pat-003',
    name: 'Amit Singh',
    age: 45,
    gender: 'Male',
    phone: '+91 99887 76655',
    email: 'amit.singh@email.com',
    address: '7, MG Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    insuranceType: 'Ayushman Bharat - PMJAY',
    insuranceId: 'PMJAY-KA-445566',
    conditions: ['Coronary Artery Disease', 'Hyperlipidemia'],
    medications: ['Aspirin 75mg', 'Rosuvastatin 20mg', 'Metoprolol 50mg'],
    allergies: ['Sulfa drugs'],
    bloodGroup: 'B+',
    lastVisit: '2026-03-26',
    nextAppointment: '2026-03-31',
    riskScore: 78,
    satisfactionScore: 82,
    vitals: { bp: '142/90', heartRate: 80, spO2: 96, bloodGlucose: 135, temperature: 36.7, weight: 88 },
  },
  {
    id: 'pat-004',
    name: 'Sunita Devi',
    age: 67,
    gender: 'Female',
    phone: '+91 77665 54433',
    email: 'sunita.devi@email.com',
    address: '23, Gomti Nagar',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    insuranceType: 'CGHS',
    insuranceId: 'CGHS-2025-998877',
    conditions: ['Osteoarthritis', 'Type 2 Diabetes', 'Hypothyroidism'],
    medications: ['Metformin 1000mg', 'Levothyroxine 50mcg', 'Diclofenac Gel'],
    allergies: ['Ibuprofen'],
    bloodGroup: 'AB+',
    lastVisit: '2026-03-24',
    nextAppointment: '2026-04-01',
    riskScore: 85,
    satisfactionScore: 76,
    vitals: { bp: '150/94', heartRate: 84, spO2: 95, bloodGlucose: 162, temperature: 36.8, weight: 72 },
  },
  {
    id: 'pat-005',
    name: 'Vikram Patel',
    age: 29,
    gender: 'Male',
    phone: '+91 88776 65544',
    email: 'vikram.patel@email.com',
    address: '8, SG Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
    insuranceType: 'ICICI Lombard',
    insuranceId: 'ICL-2026-334455',
    conditions: [],
    medications: [],
    allergies: ['Latex'],
    bloodGroup: 'O-',
    lastVisit: '2026-03-28',
    nextAppointment: '2026-04-10',
    riskScore: 12,
    satisfactionScore: 92,
    vitals: { bp: '120/78', heartRate: 66, spO2: 99, bloodGlucose: 88, temperature: 36.5, weight: 74 },
  },
]

export const demoClaims: Claim[] = [
  {
    id: 'CLM-2026-0042',
    patientId: 'pat-001',
    patientName: 'Rajesh Kumar',
    department: 'Cardiology',
    diagnosis: 'Unstable Angina',
    icdCodes: ['I20.0'],
    cptCodes: ['93458'],
    amount: 185000,
    payer: 'Star Health Insurance',
    status: 'Approved',
    submittedDate: '2026-03-18',
    lastUpdated: '2026-03-22',
    assignedTo: 'Dr. Meena Rao',
    preAuthProbability: 94,
    completenessScore: 98,
  },
  {
    id: 'CLM-2026-0043',
    patientId: 'pat-003',
    patientName: 'Amit Singh',
    department: 'Cardiology',
    diagnosis: 'Coronary Artery Bypass',
    icdCodes: ['I25.10'],
    cptCodes: ['33533'],
    amount: 450000,
    payer: 'Ayushman Bharat - PMJAY',
    status: 'Under Review',
    submittedDate: '2026-03-25',
    lastUpdated: '2026-03-27',
    assignedTo: 'Dr. Priya Sharma',
    preAuthProbability: 82,
    completenessScore: 91,
  },
  {
    id: 'CLM-2026-0044',
    patientId: 'pat-002',
    patientName: 'Priya Mehta',
    department: 'Pulmonology',
    diagnosis: 'Acute Asthma Exacerbation',
    icdCodes: ['J45.21'],
    cptCodes: ['94060'],
    amount: 32000,
    payer: 'HDFC ERGO',
    status: 'Submitted',
    submittedDate: '2026-03-27',
    lastUpdated: '2026-03-27',
    assignedTo: 'Neha Gupta',
    preAuthProbability: 88,
    completenessScore: 95,
  },
  {
    id: 'CLM-2026-0045',
    patientId: 'pat-004',
    patientName: 'Sunita Devi',
    department: 'Orthopedics',
    diagnosis: 'Total Knee Replacement',
    icdCodes: ['M17.11'],
    cptCodes: ['27447'],
    amount: 320000,
    payer: 'CGHS',
    status: 'Draft',
    submittedDate: '2026-03-28',
    lastUpdated: '2026-03-28',
    assignedTo: 'Dr. Priya Sharma',
    preAuthProbability: 75,
    completenessScore: 68,
  },
  {
    id: 'CLM-2026-0046',
    patientId: 'pat-005',
    patientName: 'Vikram Patel',
    department: 'Emergency',
    diagnosis: 'Fracture, Right Radius',
    icdCodes: ['S52.501A'],
    cptCodes: ['25600'],
    amount: 45000,
    payer: 'ICICI Lombard',
    status: 'Paid',
    submittedDate: '2026-03-15',
    lastUpdated: '2026-03-26',
    assignedTo: 'Neha Gupta',
    preAuthProbability: 96,
    completenessScore: 100,
  },
  {
    id: 'CLM-2026-0038',
    patientId: 'pat-001',
    patientName: 'Rajesh Kumar',
    department: 'Internal Medicine',
    diagnosis: 'Diabetes Management Follow-up',
    icdCodes: ['E11.65'],
    cptCodes: ['99214'],
    amount: 8500,
    payer: 'Star Health Insurance',
    status: 'Rejected',
    submittedDate: '2026-03-10',
    lastUpdated: '2026-03-20',
    assignedTo: 'Dr. Meena Rao',
    preAuthProbability: 45,
    completenessScore: 72,
    rejectionReason: 'Incomplete documentation — missing lab reports',
  },
]

export const demoAppointments: Appointment[] = [
  {
    id: 'apt-001',
    patientId: 'pat-001',
    patientName: 'Rajesh Kumar',
    doctorName: 'Dr. Anil Kapoor',
    department: 'Cardiology',
    date: '2026-03-30',
    time: '10:00 AM',
    type: 'Follow-up',
    status: 'Scheduled',
  },
  {
    id: 'apt-002',
    patientId: 'pat-004',
    patientName: 'Sunita Devi',
    doctorName: 'Dr. Ravi Shankar',
    department: 'Orthopedics',
    date: '2026-03-30',
    time: '11:30 AM',
    type: 'Consultation',
    status: 'Scheduled',
  },
  {
    id: 'apt-003',
    patientId: 'pat-002',
    patientName: 'Priya Mehta',
    doctorName: 'Dr. Kavita Nair',
    department: 'Pulmonology',
    date: '2026-03-30',
    time: '2:00 PM',
    type: 'Follow-up',
    status: 'Scheduled',
  },
  {
    id: 'apt-004',
    patientId: 'pat-003',
    patientName: 'Amit Singh',
    doctorName: 'Dr. Anil Kapoor',
    department: 'Cardiology',
    date: '2026-03-31',
    time: '9:00 AM',
    type: 'Procedure',
    status: 'Scheduled',
  },
  {
    id: 'apt-005',
    patientId: 'pat-005',
    patientName: 'Vikram Patel',
    doctorName: 'Dr. Sunil Yadav',
    department: 'Orthopedics',
    date: '2026-03-31',
    time: '3:00 PM',
    type: 'Follow-up',
    status: 'Scheduled',
  },
  {
    id: 'apt-006',
    patientId: 'pat-001',
    patientName: 'Rajesh Kumar',
    doctorName: 'Dr. Meera Joshi',
    department: 'Internal Medicine',
    date: '2026-04-02',
    time: '10:30 AM',
    type: 'Lab Test',
    status: 'Scheduled',
  },
  {
    id: 'apt-007',
    patientId: 'pat-002',
    patientName: 'Priya Mehta',
    doctorName: 'Dr. Kavita Nair',
    department: 'Pulmonology',
    date: '2026-04-05',
    time: '11:00 AM',
    type: 'Consultation',
    status: 'Scheduled',
  },
]

export const demoActivities: ActivityItem[] = [
  {
    id: 'act-001',
    action: 'Claim approved',
    subject: 'CLM-2026-0042 for Rajesh Kumar — ₹1,85,000',
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    type: 'claim',
  },
  {
    id: 'act-002',
    action: 'New patient registered',
    subject: 'Vikram Patel — Emergency Department',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    type: 'patient',
  },
  {
    id: 'act-003',
    action: 'Appointment completed',
    subject: 'Priya Mehta with Dr. Kavita Nair — Pulmonology',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    type: 'appointment',
  },
  {
    id: 'act-004',
    action: 'SLA breach warning',
    subject: 'Claim CLM-2026-0043 approaching 48hr deadline',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    type: 'alert',
  },
  {
    id: 'act-005',
    action: 'Claim submitted',
    subject: 'CLM-2026-0044 for Priya Mehta — ₹32,000',
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    type: 'claim',
  },
  {
    id: 'act-006',
    action: 'High-risk patient flagged',
    subject: 'Sunita Devi — Risk Score 85 (Vitals deteriorating)',
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    type: 'alert',
  },
  {
    id: 'act-007',
    action: 'System update deployed',
    subject: 'SmartClaims v2.4 — New auto-coding engine',
    timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
    type: 'system',
  },
  {
    id: 'act-008',
    action: 'New appointment scheduled',
    subject: 'Amit Singh with Dr. Anil Kapoor — Cardiology',
    timestamp: new Date(Date.now() - 10 * 3600000).toISOString(),
    type: 'appointment',
  },
  {
    id: 'act-009',
    action: 'Claim rejected',
    subject: 'CLM-2026-0038 for Rajesh Kumar — Missing documents',
    timestamp: new Date(Date.now() - 14 * 3600000).toISOString(),
    type: 'claim',
  },
  {
    id: 'act-010',
    action: 'Staff credential expiring',
    subject: 'Dr. Ravi Shankar — BLS certification expires Apr 5',
    timestamp: new Date(Date.now() - 18 * 3600000).toISOString(),
    type: 'system',
  },
]

export const chartData = {
  patientVisits: [
    { name: 'Mon', visits: 142, claims: 38 },
    { name: 'Tue', visits: 156, claims: 45 },
    { name: 'Wed', visits: 168, claims: 52 },
    { name: 'Thu', visits: 137, claims: 41 },
    { name: 'Fri', visits: 185, claims: 58 },
    { name: 'Sat', visits: 122, claims: 32 },
    { name: 'Sun', visits: 98, claims: 18 },
  ],
  departmentRevenue: [
    { name: 'Cardiology', revenue: 2450000 },
    { name: 'Orthopedics', revenue: 1870000 },
    { name: 'Neurology', revenue: 1540000 },
    { name: 'Oncology', revenue: 1320000 },
    { name: 'Pulmonology', revenue: 980000 },
    { name: 'Pediatrics', revenue: 760000 },
    { name: 'Internal Med', revenue: 650000 },
    { name: 'Emergency', revenue: 580000 },
  ],
  claimsTrend: [
    { name: 'Oct', submitted: 142, approved: 118 },
    { name: 'Nov', submitted: 158, approved: 131 },
    { name: 'Dec', submitted: 135, approved: 114 },
    { name: 'Jan', submitted: 167, approved: 142 },
    { name: 'Feb', submitted: 189, approved: 162 },
    { name: 'Mar', submitted: 198, approved: 174 },
  ],
  payerMix: [
    { name: 'PMJAY', value: 34, revenue: 2860000 },
    { name: 'Star Health', value: 18, revenue: 1512000 },
    { name: 'CGHS', value: 14, revenue: 1176000 },
    { name: 'HDFC ERGO', value: 12, revenue: 1008000 },
    { name: 'ICICI Lombard', value: 9, revenue: 756000 },
    { name: 'Max Bupa', value: 7, revenue: 588000 },
    { name: 'Others', value: 6, revenue: 504000 },
  ],
  churnData: [
    { name: 'Week 1', rate: 34 },
    { name: 'Week 2', rate: 28 },
    { name: 'Week 3', rate: 24 },
    { name: 'Week 4', rate: 19 },
    { name: 'Week 5', rate: 15 },
    { name: 'Week 6', rate: 12 },
    { name: 'Week 7', rate: 10 },
    { name: 'Week 8', rate: 9 },
  ],
  bedOccupancy: [
    { name: 'General', occupied: 82, total: 100 },
    { name: 'ICU', occupied: 18, total: 20 },
    { name: 'Pediatric', occupied: 22, total: 30 },
    { name: 'Maternity', occupied: 14, total: 20 },
    { name: 'Surgical', occupied: 28, total: 35 },
    { name: 'Emergency', occupied: 12, total: 15 },
  ],
  revenueByMonth: [
    { name: 'Oct', revenue: 6800000, target: 7000000 },
    { name: 'Nov', revenue: 7200000, target: 7200000 },
    { name: 'Dec', revenue: 6500000, target: 7400000 },
    { name: 'Jan', revenue: 7800000, target: 7600000 },
    { name: 'Feb', revenue: 8100000, target: 7800000 },
    { name: 'Mar', revenue: 8400000, target: 8000000 },
  ],
  departmentSatisfaction: [
    { name: 'Cardiology', score: 4.6 },
    { name: 'Orthopedics', score: 4.3 },
    { name: 'Pediatrics', score: 4.8 },
    { name: 'Emergency', score: 3.9 },
    { name: 'Oncology', score: 4.5 },
    { name: 'Neurology', score: 4.4 },
    { name: 'OB/GYN', score: 4.7 },
    { name: 'Pulmonology', score: 4.2 },
  ],
  slaCompliance: [
    { name: 'Mon', compliance: 96 },
    { name: 'Tue', compliance: 94 },
    { name: 'Wed', compliance: 92 },
    { name: 'Thu', compliance: 98 },
    { name: 'Fri', compliance: 91 },
    { name: 'Sat', compliance: 95 },
    { name: 'Sun', compliance: 97 },
  ],
  priorityDistribution: [
    { name: 'Critical', count: 2 },
    { name: 'High', count: 5 },
    { name: 'Medium', count: 3 },
    { name: 'Low', count: 2 },
  ],
  portfolioByScheme: [
    { name: 'Ayushman Bharat', value: 40 },
    { name: 'CGHS', value: 15 },
    { name: 'ECHS', value: 10 },
    { name: 'Private', value: 25 },
    { name: 'Other', value: 10 },
  ],
  fraudSavings: [
    { name: 'Oct', savings: 12 },
    { name: 'Nov', savings: 18 },
    { name: 'Dec', savings: 8 },
    { name: 'Jan', savings: 22 },
    { name: 'Feb', savings: 15 },
    { name: 'Mar', savings: 45 },
  ],
  lossRatio: [
    { name: 'Oct', ratio: 72 },
    { name: 'Nov', ratio: 68 },
    { name: 'Dec', ratio: 74 },
    { name: 'Jan', ratio: 65 },
    { name: 'Feb', ratio: 70 },
    { name: 'Mar', ratio: 63 },
  ],
  claimsByScheme: [
    { name: 'PMJAY', claims: 142 },
    { name: 'CGHS', claims: 58 },
    { name: 'ECHS', claims: 34 },
    { name: 'Private', claims: 86 },
    { name: 'ESI', claims: 22 },
  ],
}

// ── Staff / Workforce ──────────────────────────────────────────────────
export const demoStaff: Staff[] = [
  {
    id: 'STF-001', name: 'Dr. Priya Sharma', role: 'Cardiologist', department: 'Cardiology',
    email: 'priya.sharma@ayushmanlife.in', phone: '+91 98100 10001', joinDate: '2021-03-15',
    certifications: [
      { name: 'MBBS', issuer: 'AIIMS Delhi', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MD Cardiology', issuer: 'AIIMS Delhi', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'BLS Certification', issuer: 'AHA', expiryDate: '2026-04-10', status: 'Expiring', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 2 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-002', name: 'Amit Verma', role: 'IT Administrator', department: 'IT',
    email: 'amit.verma@ayushmanlife.in', phone: '+91 98100 10002', joinDate: '2020-07-01',
    certifications: [
      { name: 'AWS Solutions Architect', issuer: 'Amazon', expiryDate: '2026-08-15', status: 'Active', verified: true },
      { name: 'ITIL v4 Foundation', issuer: 'Axelos', expiryDate: '2025-12-01', status: 'Expired', verified: false },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 5 },
      { skill: 'Cloud', level: 5 }, { skill: 'Data Analytics', level: 4 }, { skill: 'Cybersecurity', level: 4 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-003', name: 'Dr. Neha Gupta', role: 'Neurologist', department: 'Neurology',
    email: 'neha.gupta@ayushmanlife.in', phone: '+91 98100 10003', joinDate: '2022-01-10',
    certifications: [
      { name: 'MBBS', issuer: 'CMC Vellore', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'DM Neurology', issuer: 'CMC Vellore', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 1 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
  {
    id: 'STF-004', name: 'Rajesh Kumar', role: 'ServiceNow Developer', department: 'IT',
    email: 'rajesh.kumar@ayushmanlife.in', phone: '+91 98100 10004', joinDate: '2021-09-20',
    certifications: [
      { name: 'ServiceNow CSA', issuer: 'ServiceNow', expiryDate: '2026-04-20', status: 'Expiring', verified: true },
      { name: 'ITSM Specialist', issuer: 'ServiceNow', expiryDate: '2027-02-28', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 5 },
      { skill: 'Cloud', level: 3 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 2 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-005', name: 'Suman Devi', role: 'Nurse Manager', department: 'Emergency',
    email: 'suman.devi@ayushmanlife.in', phone: '+91 98100 10005', joinDate: '2019-05-12',
    certifications: [
      { name: 'BSc Nursing', issuer: 'Rajiv Gandhi University', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'ACLS Certification', issuer: 'AHA', expiryDate: '2026-04-05', status: 'Expiring', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 4 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 1 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 1 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Night', status: 'Active',
  },
  {
    id: 'STF-006', name: 'Dr. Vikram Singh', role: 'Orthopedic Surgeon', department: 'Orthopedics',
    email: 'vikram.singh@ayushmanlife.in', phone: '+91 98100 10006', joinDate: '2020-11-01',
    certifications: [
      { name: 'MBBS', issuer: 'MAMC Delhi', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MS Orthopedics', issuer: 'MAMC Delhi', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'On Leave',
  },
  {
    id: 'STF-007', name: 'Ananya Patel', role: 'Data Analyst', department: 'Analytics',
    email: 'ananya.patel@ayushmanlife.in', phone: '+91 98100 10007', joinDate: '2023-02-01',
    certifications: [
      { name: 'Google Data Analytics', issuer: 'Google', expiryDate: '2027-02-01', status: 'Active', verified: true },
      { name: 'Tableau Desktop Specialist', issuer: 'Tableau', expiryDate: '2027-06-15', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 1 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 2 },
      { skill: 'Cloud', level: 3 }, { skill: 'Data Analytics', level: 5 }, { skill: 'Cybersecurity', level: 2 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-008', name: 'Mohammed Irfan', role: 'Security Engineer', department: 'IT',
    email: 'mohammed.irfan@ayushmanlife.in', phone: '+91 98100 10008', joinDate: '2022-06-15',
    certifications: [
      { name: 'CISSP', issuer: 'ISC2', expiryDate: '2027-06-15', status: 'Active', verified: true },
      { name: 'CEH', issuer: 'EC-Council', expiryDate: '2026-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 3 },
      { skill: 'Cloud', level: 4 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 5 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
  {
    id: 'STF-009', name: 'Dr. Lakshmi Menon', role: 'Pediatrician', department: 'Pediatrics',
    email: 'lakshmi.menon@ayushmanlife.in', phone: '+91 98100 10009', joinDate: '2021-08-20',
    certifications: [
      { name: 'MBBS', issuer: 'JIPMER', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MD Pediatrics', issuer: 'JIPMER', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 1 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'On Leave',
  },
  {
    id: 'STF-010', name: 'Ravi Shankar', role: 'Cloud Architect', department: 'IT',
    email: 'ravi.shankar@ayushmanlife.in', phone: '+91 98100 10010', joinDate: '2022-03-01',
    certifications: [
      { name: 'Azure Solutions Architect', issuer: 'Microsoft', expiryDate: '2027-03-01', status: 'Active', verified: true },
      { name: 'GCP Professional', issuer: 'Google', expiryDate: '2027-09-01', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 4 },
      { skill: 'Cloud', level: 5 }, { skill: 'Data Analytics', level: 4 }, { skill: 'Cybersecurity', level: 3 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-011', name: 'Divya Rao', role: 'EMR Specialist', department: 'Health Informatics',
    email: 'divya.rao@ayushmanlife.in', phone: '+91 98100 10011', joinDate: '2021-11-15',
    certifications: [
      { name: 'Epic Certification', issuer: 'Epic Systems', expiryDate: '2026-11-15', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 2 }, { skill: 'EMR/EHR', level: 5 }, { skill: 'ServiceNow', level: 3 },
      { skill: 'Cloud', level: 2 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 2 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
  {
    id: 'STF-012', name: 'Karthik Nair', role: 'Lab Technician', department: 'Pathology',
    email: 'karthik.nair@ayushmanlife.in', phone: '+91 98100 10012', joinDate: '2023-05-01',
    certifications: [
      { name: 'DMLT', issuer: 'Kerala University', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 3 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Night', status: 'Training',
  },
  {
    id: 'STF-013', name: 'Dr. Arun Joshi', role: 'Oncologist', department: 'Oncology',
    email: 'arun.joshi@ayushmanlife.in', phone: '+91 98100 10013', joinDate: '2020-04-10',
    certifications: [
      { name: 'MBBS', issuer: 'TMC Mumbai', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'DM Medical Oncology', issuer: 'TMC Mumbai', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-014', name: 'Meera Reddy', role: 'Claims Processor', department: 'Revenue Cycle',
    email: 'meera.reddy@ayushmanlife.in', phone: '+91 98100 10014', joinDate: '2022-08-01',
    certifications: [
      { name: 'CPC Certification', issuer: 'AAPC', expiryDate: '2026-08-01', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 2 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 2 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-015', name: 'Suresh Pillai', role: 'Network Engineer', department: 'IT',
    email: 'suresh.pillai@ayushmanlife.in', phone: '+91 98100 10015', joinDate: '2021-12-01',
    certifications: [
      { name: 'CCNP', issuer: 'Cisco', expiryDate: '2025-11-30', status: 'Expired', verified: false },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 1 }, { skill: 'ServiceNow', level: 3 },
      { skill: 'Cloud', level: 4 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 4 },
    ],
    shift: 'Night', status: 'Active',
  },
  {
    id: 'STF-016', name: 'Dr. Fatima Khan', role: 'Radiologist', department: 'Radiology',
    email: 'fatima.khan@ayushmanlife.in', phone: '+91 98100 10016', joinDate: '2022-05-10',
    certifications: [
      { name: 'MBBS', issuer: 'AMU Aligarh', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MD Radiology', issuer: 'AMU Aligarh', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 4 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
  {
    id: 'STF-017', name: 'Pooja Mishra', role: 'HR Manager', department: 'Human Resources',
    email: 'pooja.mishra@ayushmanlife.in', phone: '+91 98100 10017', joinDate: '2020-02-15',
    certifications: [
      { name: 'SHRM-CP', issuer: 'SHRM', expiryDate: '2027-02-15', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 1 }, { skill: 'ServiceNow', level: 3 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-018', name: 'Arjun Das', role: 'Pharmacist', department: 'Pharmacy',
    email: 'arjun.das@ayushmanlife.in', phone: '+91 98100 10018', joinDate: '2023-01-15',
    certifications: [
      { name: 'B.Pharm', issuer: 'Manipal University', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 3 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 1 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
  {
    id: 'STF-019', name: 'Sneha Kulkarni', role: 'Quality Analyst', department: 'Quality Assurance',
    email: 'sneha.kulkarni@ayushmanlife.in', phone: '+91 98100 10019', joinDate: '2022-10-01',
    certifications: [
      { name: 'NABH Assessor', issuer: 'NABH', expiryDate: '2026-10-01', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 2 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 2 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 4 }, { skill: 'Cybersecurity', level: 2 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-020', name: 'Dr. Sanjay Mehta', role: 'General Surgeon', department: 'General Surgery',
    email: 'sanjay.mehta@ayushmanlife.in', phone: '+91 98100 10020', joinDate: '2019-08-01',
    certifications: [
      { name: 'MBBS', issuer: 'KEM Mumbai', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MS General Surgery', issuer: 'KEM Mumbai', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 1 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'On Leave',
  },
  {
    id: 'STF-021', name: 'Tanvi Bhatt', role: 'Physiotherapist', department: 'Rehabilitation',
    email: 'tanvi.bhatt@ayushmanlife.in', phone: '+91 98100 10021', joinDate: '2023-03-15',
    certifications: [
      { name: 'BPT', issuer: 'Gujarat University', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 4 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 1 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-022', name: 'Deepak Chauhan', role: 'DevOps Engineer', department: 'IT',
    email: 'deepak.chauhan@ayushmanlife.in', phone: '+91 98100 10022', joinDate: '2022-04-01',
    certifications: [
      { name: 'Kubernetes Administrator', issuer: 'CNCF', expiryDate: '2026-04-01', status: 'Expiring', verified: true },
      { name: 'Docker Certified Associate', issuer: 'Docker', expiryDate: '2027-01-15', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 0 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 4 },
      { skill: 'Cloud', level: 5 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 3 },
    ],
    shift: 'Night', status: 'Active',
  },
  {
    id: 'STF-023', name: 'Nisha Agarwal', role: 'Billing Coordinator', department: 'Revenue Cycle',
    email: 'nisha.agarwal@ayushmanlife.in', phone: '+91 98100 10023', joinDate: '2021-06-01',
    certifications: [
      { name: 'CCS Certification', issuer: 'AHIMA', expiryDate: '2026-06-01', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 1 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 2 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-024', name: 'Dr. Rohan Saxena', role: 'Psychiatrist', department: 'Psychiatry',
    email: 'rohan.saxena@ayushmanlife.in', phone: '+91 98100 10024', joinDate: '2022-09-01',
    certifications: [
      { name: 'MBBS', issuer: 'NIMHANS', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MD Psychiatry', issuer: 'NIMHANS', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 5 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
  {
    id: 'STF-025', name: 'Kavita Sharma', role: 'Staff Nurse', department: 'Internal Medicine',
    email: 'kavita.sharma@ayushmanlife.in', phone: '+91 98100 10025', joinDate: '2020-10-01',
    certifications: [
      { name: 'GNM Nursing', issuer: 'Delhi University', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 4 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 1 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Night', status: 'Active',
  },
  {
    id: 'STF-026', name: 'Vinod Tiwari', role: 'EHR Trainer', department: 'Health Informatics',
    email: 'vinod.tiwari@ayushmanlife.in', phone: '+91 98100 10026', joinDate: '2021-04-15',
    certifications: [
      { name: 'Cerner Millennium Certified', issuer: 'Oracle Cerner', expiryDate: '2026-04-15', status: 'Expiring', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 1 }, { skill: 'EMR/EHR', level: 5 }, { skill: 'ServiceNow', level: 2 },
      { skill: 'Cloud', level: 2 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 1 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-027', name: 'Swati Jain', role: 'Clinical Coder', department: 'Revenue Cycle',
    email: 'swati.jain@ayushmanlife.in', phone: '+91 98100 10027', joinDate: '2023-07-01',
    certifications: [
      { name: 'CPC-A', issuer: 'AAPC', expiryDate: '2027-07-01', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 2 }, { skill: 'EMR/EHR', level: 4 }, { skill: 'ServiceNow', level: 1 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-028', name: 'Dr. Asha Nair', role: 'Dermatologist', department: 'Dermatology',
    email: 'asha.nair@ayushmanlife.in', phone: '+91 98100 10028', joinDate: '2022-02-15',
    certifications: [
      { name: 'MBBS', issuer: 'Seth GS Mumbai', expiryDate: '2030-12-31', status: 'Active', verified: true },
      { name: 'MD Dermatology', issuer: 'Seth GS Mumbai', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 4 }, { skill: 'EMR/EHR', level: 3 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-029', name: 'Rahul Pandey', role: 'Compliance Officer', department: 'Quality Assurance',
    email: 'rahul.pandey@ayushmanlife.in', phone: '+91 98100 10029', joinDate: '2021-01-10',
    certifications: [
      { name: 'CHC Certification', issuer: 'HCCA', expiryDate: '2026-01-10', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 1 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 3 },
      { skill: 'Cloud', level: 1 }, { skill: 'Data Analytics', level: 3 }, { skill: 'Cybersecurity', level: 3 },
    ],
    shift: 'Morning', status: 'Active',
  },
  {
    id: 'STF-030', name: 'Preeti Saxena', role: 'Dietitian', department: 'Internal Medicine',
    email: 'preeti.saxena@ayushmanlife.in', phone: '+91 98100 10030', joinDate: '2023-09-01',
    certifications: [
      { name: 'BSc Nutrition', issuer: 'BHU', expiryDate: '2030-12-31', status: 'Active', verified: true },
    ],
    skills: [
      { skill: 'Clinical', level: 3 }, { skill: 'EMR/EHR', level: 2 }, { skill: 'ServiceNow', level: 0 },
      { skill: 'Cloud', level: 0 }, { skill: 'Data Analytics', level: 2 }, { skill: 'Cybersecurity', level: 0 },
    ],
    shift: 'Afternoon', status: 'Active',
  },
]

// ── Tickets / Managed Services ─────────────────────────────────────────
export const demoTickets: Ticket[] = [
  { id: 'TKT-001', title: 'EMR system slow during peak hours', description: 'Multiple users reporting EMR response time > 5s during 10 AM - 12 PM.', priority: 'Critical', status: 'Open', assignee: 'Amit Verma', createdDate: '2026-03-28T09:15:00', slaDeadline: '2026-03-28T13:15:00', category: 'EMR/EHR' },
  { id: 'TKT-002', title: 'ServiceNow workflow approval stuck', description: 'Change request CR-2048 stuck in approval loop.', priority: 'High', status: 'In Progress', assignee: 'Rajesh Kumar', createdDate: '2026-03-27T14:30:00', slaDeadline: '2026-03-28T14:30:00', category: 'ServiceNow' },
  { id: 'TKT-003', title: 'VPN connectivity issues from Hyderabad office', description: 'Staff unable to connect to VPN from Hyderabad branch.', priority: 'High', status: 'Open', assignee: 'Suresh Pillai', createdDate: '2026-03-28T08:00:00', slaDeadline: '2026-03-29T08:00:00', category: 'Infrastructure' },
  { id: 'TKT-004', title: 'New user onboarding - batch 15 accounts', description: 'Create accounts for 15 new hires starting April 1.', priority: 'Medium', status: 'In Progress', assignee: 'Amit Verma', createdDate: '2026-03-25T10:00:00', slaDeadline: '2026-03-30T10:00:00', category: 'User Management' },
  { id: 'TKT-005', title: 'Printer offline - Cardiology wing', description: 'Network printer in Cardiology ward showing offline status.', priority: 'Low', status: 'Resolved', assignee: 'Suresh Pillai', createdDate: '2026-03-26T11:30:00', slaDeadline: '2026-03-28T11:30:00', category: 'Infrastructure' },
  { id: 'TKT-006', title: 'Data backup failure alert', description: 'Nightly backup job for patient database failed with timeout error.', priority: 'Critical', status: 'In Progress', assignee: 'Deepak Chauhan', createdDate: '2026-03-28T06:00:00', slaDeadline: '2026-03-28T10:00:00', category: 'Infrastructure' },
  { id: 'TKT-007', title: 'Claims portal 502 errors', description: 'Intermittent 502 errors on claims submission portal.', priority: 'High', status: 'Open', assignee: 'Ravi Shankar', createdDate: '2026-03-28T07:45:00', slaDeadline: '2026-03-29T07:45:00', category: 'EMR/EHR' },
  { id: 'TKT-008', title: 'Security patch deployment - Windows servers', description: 'Monthly security patches for 24 Windows servers.', priority: 'Medium', status: 'Open', assignee: 'Mohammed Irfan', createdDate: '2026-03-27T09:00:00', slaDeadline: '2026-03-31T09:00:00', category: 'Security' },
  { id: 'TKT-009', title: 'Password reset requests (bulk)', description: '8 staff members locked out after password policy change.', priority: 'Medium', status: 'Resolved', assignee: 'Amit Verma', createdDate: '2026-03-27T08:30:00', slaDeadline: '2026-03-27T16:30:00', category: 'User Management' },
  { id: 'TKT-010', title: 'PACS integration with new MRI machine', description: 'Configure DICOM integration for Siemens 3T MRI installed this week.', priority: 'High', status: 'In Progress', assignee: 'Divya Rao', createdDate: '2026-03-26T13:00:00', slaDeadline: '2026-03-29T13:00:00', category: 'EMR/EHR' },
  { id: 'TKT-011', title: 'Email delivery delays', description: 'Outbound emails taking 15-30 minutes to deliver.', priority: 'Low', status: 'Closed', assignee: 'Suresh Pillai', createdDate: '2026-03-24T10:00:00', slaDeadline: '2026-03-26T10:00:00', category: 'Infrastructure' },
  { id: 'TKT-012', title: 'Dashboard performance optimization', description: 'Analytics dashboard loading time exceeds 8 seconds.', priority: 'High', status: 'Open', assignee: 'Ananya Patel', createdDate: '2026-03-28T10:00:00', slaDeadline: '2026-03-30T10:00:00', category: 'EMR/EHR' },
]

// ── Policies ───────────────────────────────────────────────────────────
export const demoPolicies: Policy[] = [
  { id: 'POL-001', policyNumber: 'AB-PMJAY-2024-10001', scheme: 'Ayushman Bharat - PMJAY', beneficiaryName: 'Rajesh Khanna', status: 'Active', startDate: '2024-04-01', endDate: '2027-03-31', sumInsured: 500000, premium: 0, claimsCount: 2 },
  { id: 'POL-002', policyNumber: 'CGHS-2023-20045', scheme: 'CGHS', beneficiaryName: 'Sunita Devi', status: 'Active', startDate: '2023-01-01', endDate: '2026-12-31', sumInsured: 1000000, premium: 12000, claimsCount: 1 },
  { id: 'POL-003', policyNumber: 'SHI-2025-30078', scheme: 'Star Health Insurance', beneficiaryName: 'Mohammed Ali', status: 'Active', startDate: '2025-06-15', endDate: '2026-06-14', sumInsured: 1500000, premium: 18500, claimsCount: 1 },
  { id: 'POL-004', policyNumber: 'AB-PMJAY-2024-10089', scheme: 'Ayushman Bharat - PMJAY', beneficiaryName: 'Anita Kumari', status: 'Active', startDate: '2024-04-01', endDate: '2027-03-31', sumInsured: 500000, premium: 0, claimsCount: 1 },
  { id: 'POL-005', policyNumber: 'ECHS-2024-40012', scheme: 'ECHS', beneficiaryName: 'Vikram Rathore', status: 'Active', startDate: '2024-01-01', endDate: '2026-12-31', sumInsured: 750000, premium: 0, claimsCount: 1 },
  { id: 'POL-006', policyNumber: 'HDFC-2024-50034', scheme: 'HDFC ERGO', beneficiaryName: 'Priya Chopra', status: 'Active', startDate: '2024-09-01', endDate: '2025-08-31', sumInsured: 500000, premium: 14200, claimsCount: 1 },
  { id: 'POL-007', policyNumber: 'ICICI-2025-60023', scheme: 'ICICI Lombard', beneficiaryName: 'Arjun Malhotra', status: 'Active', startDate: '2025-02-01', endDate: '2026-01-31', sumInsured: 1000000, premium: 16800, claimsCount: 1 },
  { id: 'POL-008', policyNumber: 'AB-PMJAY-2024-10145', scheme: 'Ayushman Bharat - PMJAY', beneficiaryName: 'Kavita Patel', status: 'Active', startDate: '2024-04-01', endDate: '2027-03-31', sumInsured: 500000, premium: 0, claimsCount: 1 },
  { id: 'POL-009', policyNumber: 'MB-2025-70056', scheme: 'Max Bupa', beneficiaryName: 'Suresh Yadav', status: 'Active', startDate: '2025-01-01', endDate: '2025-12-31', sumInsured: 2000000, premium: 22000, claimsCount: 1 },
  { id: 'POL-010', policyNumber: 'NIA-2024-80019', scheme: 'New India Assurance', beneficiaryName: 'Deepa Sharma', status: 'Active', startDate: '2024-07-01', endDate: '2025-06-30', sumInsured: 300000, premium: 8500, claimsCount: 1 },
  { id: 'POL-011', policyNumber: 'CGHS-2022-20012', scheme: 'CGHS', beneficiaryName: 'Ramesh Gupta', status: 'Active', startDate: '2022-01-01', endDate: '2026-12-31', sumInsured: 1000000, premium: 12000, claimsCount: 2 },
  { id: 'POL-012', policyNumber: 'AB-PMJAY-2023-10200', scheme: 'Ayushman Bharat - PMJAY', beneficiaryName: 'Lakshmi Iyer', status: 'Active', startDate: '2023-04-01', endDate: '2026-03-31', sumInsured: 500000, premium: 0, claimsCount: 1 },
  { id: 'POL-013', policyNumber: 'ESI-2024-90034', scheme: 'ESI', beneficiaryName: 'Manoj Kumar', status: 'Expired', startDate: '2024-01-01', endDate: '2025-12-31', sumInsured: 200000, premium: 0, claimsCount: 0 },
  { id: 'POL-014', policyNumber: 'SHI-2023-30050', scheme: 'Star Health Insurance', beneficiaryName: 'Geeta Rani', status: 'Lapsed', startDate: '2023-03-01', endDate: '2024-02-28', sumInsured: 500000, premium: 15000, claimsCount: 0 },
  { id: 'POL-015', policyNumber: 'AB-PMJAY-2025-10300', scheme: 'Ayushman Bharat - PMJAY', beneficiaryName: 'Santosh Verma', status: 'Pending', startDate: '2025-04-01', endDate: '2028-03-31', sumInsured: 500000, premium: 0, claimsCount: 0 },
]

// ── Fraud Alerts ───────────────────────────────────────────────────────
export const demoFraudAlerts: FraudAlert[] = [
  { id: 'FRD-001', claimId: 'CLM-8001', riskScore: 92, anomalyType: 'Duplicate Billing', provider: 'City Care Hospital', amount: 285000, status: 'Under Investigation', detectedDate: '2026-03-27' },
  { id: 'FRD-002', claimId: 'CLM-8002', riskScore: 87, anomalyType: 'Upcoding', provider: 'Metro Health Clinic', amount: 178000, status: 'Confirmed', detectedDate: '2026-03-26' },
  { id: 'FRD-003', claimId: 'CLM-8003', riskScore: 78, anomalyType: 'Phantom Billing', provider: 'Sunrise Medical Centre', amount: 95000, status: 'Under Investigation', detectedDate: '2026-03-25' },
  { id: 'FRD-004', claimId: 'CLM-8004', riskScore: 65, anomalyType: 'Unbundling', provider: 'Green Valley Hospital', amount: 142000, status: 'Cleared', detectedDate: '2026-03-24' },
  { id: 'FRD-005', claimId: 'CLM-8005', riskScore: 91, anomalyType: 'Identity Fraud', provider: 'LifeLine Diagnostics', amount: 320000, status: 'Confirmed', detectedDate: '2026-03-23' },
  { id: 'FRD-006', claimId: 'CLM-8006', riskScore: 55, anomalyType: 'Excessive Services', provider: 'Apollo Reach', amount: 68000, status: 'Cleared', detectedDate: '2026-03-22' },
  { id: 'FRD-007', claimId: 'CLM-8007', riskScore: 83, anomalyType: 'Duplicate Billing', provider: 'Medanta Referral', amount: 210000, status: 'Under Investigation', detectedDate: '2026-03-21' },
  { id: 'FRD-008', claimId: 'CLM-8008', riskScore: 72, anomalyType: 'Upcoding', provider: 'SafeHands Clinic', amount: 156000, status: 'Under Investigation', detectedDate: '2026-03-20' },
]
