// PDF Generation utilities using jspdf
import { jsPDF } from 'jspdf';

const BRAND_COLOR = [15, 82, 186] as const; // AyushmanLife blue
const CURRENCY = '₹';

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text('AyushmanLife', 14, 14);
  doc.setFontSize(12);
  doc.text(title, 14, 22);
  if (subtitle) {
    doc.setFontSize(9);
    doc.text(subtitle, 210 - 14, 22, { align: 'right' });
  }
  doc.setTextColor(0, 0, 0);
  return 35; // y position after header
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated by AyushmanLife Platform — ${new Date().toLocaleDateString('en-IN')}`, 14, 287);
    doc.text(`Page ${i} of ${pageCount}`, 196, 287, { align: 'right' });
  }
}

function addSection(doc: jsPDF, y: number, title: string): number {
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_COLOR);
  doc.text(title, 14, y);
  doc.setDrawColor(...BRAND_COLOR);
  doc.line(14, y + 1, 196, y + 1);
  doc.setTextColor(0, 0, 0);
  return y + 8;
}

function addKeyValue(doc: jsPDF, y: number, key: string, value: string | number, indent = 14): number {
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(key, indent, y);
  doc.setTextColor(0, 0, 0);
  doc.text(String(value), indent + 60, y);
  return y + 6;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number = 30): number {
  if (y + needed > 280) {
    doc.addPage();
    return 20;
  }
  return y;
}

// ---- Public generators ----

export function generateIRDAIReport(data: Record<string, unknown>): jsPDF {
  const doc = new jsPDF();
  const exec = data.executive_summary as Record<string, number> | undefined;
  const period = (data.period as string) || new Date().toLocaleDateString('en-IN');

  let y = addHeader(doc, 'IRDAI Regulatory Compliance Report', `Period: ${period}`);

  // Executive Summary
  y = addSection(doc, y, 'Executive Summary');
  if (exec) {
    y = addKeyValue(doc, y, 'Total Premium Collected', `${CURRENCY}${(exec.total_premium_collected || 0).toLocaleString('en-IN')}`);
    y = addKeyValue(doc, y, 'Total Claims Incurred', `${CURRENCY}${(exec.total_claims_incurred || 0).toLocaleString('en-IN')}`);
    y = addKeyValue(doc, y, 'Overall Loss Ratio', `${((exec.overall_loss_ratio || 0) * 100).toFixed(1)}%`);
    y = addKeyValue(doc, y, 'Settlement Rate', `${((exec.settlement_rate || 0) * 100).toFixed(1)}%`);
    y = addKeyValue(doc, y, 'Total Lives Covered', (exec.total_lives_covered || 0).toLocaleString('en-IN'));
    y = addKeyValue(doc, y, 'Unique Claimants', (exec.unique_claimants || 0).toLocaleString('en-IN'));
    y = addKeyValue(doc, y, 'Fraud Cases Detected', String(exec.fraud_cases_detected || 0));
    y = addKeyValue(doc, y, 'Fraud Recovery', `${CURRENCY}${(exec.fraud_recovery || 0).toLocaleString('en-IN')}`);
  }

  y = checkPageBreak(doc, y + 5);

  // Loss Ratio Analysis
  const lra = data.loss_ratio_analysis as Record<string, unknown> | undefined;
  if (lra) {
    y = addSection(doc, y, 'Loss Ratio Analysis');
    y = addKeyValue(doc, y, 'Overall Loss Ratio', `${(((lra.overall as number) || 0) * 100).toFixed(1)}%`);
    const schemes = (lra.by_scheme as Record<string, unknown>[]) || [];
    schemes.forEach(s => {
      y = checkPageBreak(doc, y);
      doc.setFontSize(9);
      doc.text(`${s.payer_scheme}: LR ${(((s.loss_ratio as number) || 0) * 100).toFixed(1)}% (Threshold: ${(((s.irdai_threshold as number) || 0) * 100).toFixed(0)}%) — ${s.compliant ? '✓ Compliant' : '✗ Non-compliant'}`, 20, y);
      y += 5;
    });
  }

  y = checkPageBreak(doc, y + 5);

  // Compliance Scorecard
  const scorecard = data.compliance_scorecard as Record<string, Record<string, number>> | undefined;
  if (scorecard) {
    y = addSection(doc, y, 'IRDAI Compliance Scorecard');
    Object.entries(scorecard).forEach(([metric, val]) => {
      y = checkPageBreak(doc, y);
      const status = val.status || (val.value >= val.threshold ? 'compliant' : 'non-compliant');
      doc.setFontSize(9);
      doc.text(`${metric}: ${typeof val.value === 'number' && val.value < 1 ? (val.value * 100).toFixed(1) + '%' : val.value} (Threshold: ${typeof val.threshold === 'number' && val.threshold < 1 ? (val.threshold * 100).toFixed(0) + '%' : val.threshold}) — ${status}`, 20, y);
      y += 5;
    });
  }

  // TAT
  y = checkPageBreak(doc, y + 5);
  const tat = data.turnaround_time as Record<string, unknown> | undefined;
  if (tat) {
    y = addSection(doc, y, 'Turnaround Time Analysis');
    y = addKeyValue(doc, y, 'IRDAI Threshold', `${tat.irdai_threshold_days || 30} days`);
    const tatSchemes = (tat.by_scheme as Record<string, unknown>[]) || [];
    tatSchemes.forEach(s => {
      y = checkPageBreak(doc, y);
      doc.setFontSize(9);
      doc.text(`${s.payer_scheme}: Avg ${(s.avg_tat_days as number || 0).toFixed(1)} days, Compliance: ${(s.tat_compliance_pct as number || 0).toFixed(0)}%`, 20, y);
      y += 5;
    });
  }

  addFooter(doc);
  return doc;
}

export function generatePolicyDocument(policy: Record<string, unknown>): jsPDF {
  const doc = new jsPDF();
  let y = addHeader(doc, 'Insurance Policy Certificate', `Policy #${policy.policy_number || ''}`);

  y = addSection(doc, y, 'Policy Details');
  y = addKeyValue(doc, y, 'Policy Number', String(policy.policy_number || ''));
  y = addKeyValue(doc, y, 'Scheme', String(policy.scheme || ''));
  y = addKeyValue(doc, y, 'Provider', String(policy.provider_name || ''));
  y = addKeyValue(doc, y, 'Policy Holder', String(policy.holder_name || policy.patient_name || ''));
  y = addKeyValue(doc, y, 'Coverage Amount', `${CURRENCY}${((policy.coverage_amount as number) || 0).toLocaleString('en-IN')}`);
  y = addKeyValue(doc, y, 'Premium Amount', `${CURRENCY}${((policy.premium_amount as number) || 0).toLocaleString('en-IN')}`);
  y = addKeyValue(doc, y, 'Start Date', String(policy.start_date || ''));
  y = addKeyValue(doc, y, 'End Date', String(policy.end_date || 'Ongoing'));
  y = addKeyValue(doc, y, 'Status', String(policy.status || ''));

  if (policy.benefits) {
    y = checkPageBreak(doc, y + 5);
    y = addSection(doc, y, 'Benefits');
    doc.setFontSize(9);
    const benefits = String(policy.benefits).split(',');
    benefits.forEach(b => {
      y = checkPageBreak(doc, y);
      doc.text(`• ${b.trim()}`, 20, y);
      y += 5;
    });
  }

  addFooter(doc);
  return doc;
}

export function generateCertificate(data: { name: string; course: string; date: string; score?: number }): jsPDF {
  const doc = new jsPDF('landscape');

  // Decorative border
  doc.setDrawColor(...BRAND_COLOR);
  doc.setLineWidth(3);
  doc.rect(10, 10, 277, 190);
  doc.setLineWidth(1);
  doc.rect(14, 14, 269, 182);

  // Title
  doc.setFontSize(32);
  doc.setTextColor(...BRAND_COLOR);
  doc.text('Certificate of Completion', 148.5, 50, { align: 'center' });

  // Decorative line
  doc.setDrawColor(200, 200, 200);
  doc.line(60, 58, 237, 58);

  // Body
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text('This is to certify that', 148.5, 75, { align: 'center' });

  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text(data.name, 148.5, 92, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text('has successfully completed the course', 148.5, 108, { align: 'center' });

  doc.setFontSize(18);
  doc.setTextColor(...BRAND_COLOR);
  doc.text(data.course, 148.5, 124, { align: 'center' });

  if (data.score !== undefined) {
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Score: ${data.score}%`, 148.5, 138, { align: 'center' });
  }

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${data.date}`, 148.5, 152, { align: 'center' });

  // Signature lines
  doc.setDrawColor(0, 0, 0);
  doc.line(40, 175, 120, 175);
  doc.line(177, 175, 257, 175);
  doc.setFontSize(10);
  doc.text('Program Director', 80, 182, { align: 'center' });
  doc.text('AyushmanLife Academy', 217, 182, { align: 'center' });

  // Logo text
  doc.setFontSize(10);
  doc.setTextColor(...BRAND_COLOR);
  doc.text('AyushmanLife Healthcare Platform', 148.5, 195, { align: 'center' });

  return doc;
}

export function generateTestReport(data: Record<string, unknown>): jsPDF {
  const doc = new jsPDF();
  const summary = data.summary as Record<string, number> | undefined;

  let y = addHeader(doc, 'EMR Test Execution Report', `Generated: ${new Date().toLocaleDateString('en-IN')}`);

  if (summary) {
    y = addSection(doc, y, 'Test Summary');
    y = addKeyValue(doc, y, 'Total Suites', String(summary.total_suites || 0));
    y = addKeyValue(doc, y, 'Total Scripts', String(summary.total_scripts || 0));
    y = addKeyValue(doc, y, 'Total Defects', String(summary.total_defects || 0));
    y = addKeyValue(doc, y, 'Pass Rate', `${(summary.pass_rate || 0).toFixed(1)}%`);
    y = addKeyValue(doc, y, 'Execution Rate', `${(summary.execution_rate || 0).toFixed(1)}%`);
  }

  // Script status breakdown
  const scriptStatus = data.script_status as Record<string, number> | undefined;
  if (scriptStatus) {
    y = checkPageBreak(doc, y + 5);
    y = addSection(doc, y, 'Script Status Breakdown');
    Object.entries(scriptStatus).forEach(([status, count]) => {
      y = addKeyValue(doc, y, status.charAt(0).toUpperCase() + status.slice(1), String(count));
    });
  }

  // Defect severity
  const defectSeverity = data.defect_severity as Record<string, number> | undefined;
  if (defectSeverity) {
    y = checkPageBreak(doc, y + 5);
    y = addSection(doc, y, 'Defect Severity');
    Object.entries(defectSeverity).forEach(([sev, count]) => {
      y = addKeyValue(doc, y, sev.charAt(0).toUpperCase() + sev.slice(1), String(count));
    });
  }

  // Suites
  const suites = data.suites as Record<string, unknown>[] | undefined;
  if (suites && suites.length > 0) {
    y = checkPageBreak(doc, y + 5);
    y = addSection(doc, y, 'Test Suites');
    doc.setFontSize(8);
    // Table header
    doc.setFillColor(240, 240, 240);
    doc.rect(14, y - 3, 182, 6, 'F');
    doc.text('Suite Name', 16, y);
    doc.text('Scripts', 100, y);
    doc.text('Passed', 120, y);
    doc.text('Failed', 140, y);
    doc.text('Status', 160, y);
    y += 6;
    suites.forEach(s => {
      y = checkPageBreak(doc, y);
      doc.text(String(s.name || '').slice(0, 40), 16, y);
      doc.text(String(s.total_scripts || 0), 100, y);
      doc.text(String(s.passed || 0), 120, y);
      doc.text(String(s.failed || 0), 140, y);
      doc.text(String(s.status || ''), 160, y);
      y += 5;
    });
  }

  addFooter(doc);
  return doc;
}

export function exportTableToPDF(title: string, headers: string[], rows: (string | number)[][]): jsPDF {
  const doc = new jsPDF();
  let y = addHeader(doc, title, new Date().toLocaleDateString('en-IN'));

  const colWidth = Math.min(180 / headers.length, 40);
  doc.setFontSize(8);

  // Header row
  doc.setFillColor(240, 240, 240);
  doc.rect(14, y - 3, 182, 6, 'F');
  headers.forEach((h, i) => {
    doc.text(String(h).slice(0, 20), 16 + i * colWidth, y);
  });
  y += 7;

  // Data rows
  rows.forEach(row => {
    y = checkPageBreak(doc, y);
    row.forEach((cell, i) => {
      doc.text(String(cell).slice(0, 20), 16 + i * colWidth, y);
    });
    y += 5;
  });

  addFooter(doc);
  return doc;
}
