name = "ayushmanlife"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ayushmanlife-db"
database_id = "a4280bab-737b-427c-bed7-49bdc5ef686e"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "ayushmanlife-files"
