-- TeleWeight: Telemedicine Weight Management Module
-- Migration 020 — Schema creation
-- Date: 2026-04-05

-- Specialist doctors panel
CREATE TABLE IF NOT EXISTS doctors (
    id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    registration_number TEXT NOT NULL,
    council_name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    qualifications TEXT NOT NULL,
    experience_years INTEGER,
    languages TEXT,
    consultation_fee INTEGER NOT NULL,
    platform_commission_pct INTEGER DEFAULT 25,
    availability_slots TEXT,
    rating REAL DEFAULT 0,
    total_consultations INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    profile_photo_r2_key TEXT,
    bio TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Patient weight management profiles (extends existing patients table)
CREATE TABLE IF NOT EXISTS patient_weight_profiles (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL UNIQUE,
    height_cm REAL,
    current_weight_kg REAL,
    target_weight_kg REAL,
    bmi REAL,
    waist_circumference_cm REAL,
    comorbidities TEXT,
    current_medications TEXT,
    allergies TEXT,
    previous_weight_treatments TEXT,
    dietary_preference TEXT,
    exercise_frequency TEXT,
    smoking_status TEXT,
    alcohol_status TEXT,
    family_history TEXT,
    intake_completed INTEGER DEFAULT 0,
    intake_completed_at TEXT,
    risk_flags TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);

-- Weight tracking logs
CREATE TABLE IF NOT EXISTS weight_logs (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL,
    weight_kg REAL NOT NULL,
    bmi REAL,
    waist_cm REAL,
    blood_glucose REAL,
    hba1c REAL,
    blood_pressure_systolic INTEGER,
    blood_pressure_diastolic INTEGER,
    notes TEXT,
    logged_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);

-- Video consultations
CREATE TABLE IF NOT EXISTS consultations (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL,
    doctor_id TEXT NOT NULL,
    consultation_type TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'video',
    status TEXT NOT NULL DEFAULT 'scheduled',
    scheduled_at TEXT NOT NULL,
    started_at TEXT,
    ended_at TEXT,
    duration_minutes INTEGER,
    consultation_fee INTEGER NOT NULL,
    platform_fee INTEGER NOT NULL,
    doctor_payout INTEGER NOT NULL,
    patient_consent_telemedicine INTEGER DEFAULT 0,
    patient_consent_data_sharing INTEGER DEFAULT 0,
    recording_consent INTEGER DEFAULT 0,
    consultation_notes TEXT,
    follow_up_recommended INTEGER DEFAULT 0,
    follow_up_weeks INTEGER,
    cancelled_by TEXT,
    cancellation_reason TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- E-Prescriptions (generated by doctor ONLY)
CREATE TABLE IF NOT EXISTS prescriptions (
    id TEXT PRIMARY KEY,
    consultation_id TEXT NOT NULL,
    patient_id TEXT NOT NULL,
    doctor_id TEXT NOT NULL,
    doctor_registration_number TEXT NOT NULL,
    prescription_date TEXT NOT NULL,
    diagnosis TEXT NOT NULL,
    medications TEXT NOT NULL,
    lifestyle_recommendations TEXT,
    lab_tests_ordered TEXT,
    follow_up_date TEXT,
    special_instructions TEXT,
    is_controlled_substance INTEGER DEFAULT 0,
    prescription_pdf_r2_key TEXT,
    status TEXT DEFAULT 'active',
    dispensed_at TEXT,
    dispensed_by_pharmacy TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (consultation_id) REFERENCES consultations(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- Pharmacy partners (licensed, verified)
CREATE TABLE IF NOT EXISTS pharmacy_partners (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    license_number TEXT NOT NULL,
    license_expiry TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    pincode TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    delivery_radius_km INTEGER DEFAULT 50,
    supports_home_delivery INTEGER DEFAULT 1,
    avg_delivery_days INTEGER DEFAULT 2,
    commission_pct INTEGER DEFAULT 8,
    is_active INTEGER DEFAULT 1,
    verified_at TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Prescription fulfillment / pharmacy orders
CREATE TABLE IF NOT EXISTS pharmacy_orders (
    id TEXT PRIMARY KEY,
    prescription_id TEXT NOT NULL,
    patient_id TEXT NOT NULL,
    pharmacy_id TEXT NOT NULL,
    order_status TEXT DEFAULT 'pending',
    delivery_address TEXT NOT NULL,
    delivery_pincode TEXT NOT NULL,
    estimated_delivery_date TEXT,
    actual_delivery_date TEXT,
    total_amount INTEGER,
    payment_status TEXT DEFAULT 'pending',
    payment_method TEXT,
    tracking_number TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (pharmacy_id) REFERENCES pharmacy_partners(id)
);

-- Subscription plans
CREATE TABLE IF NOT EXISTS subscription_plans (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price_monthly INTEGER NOT NULL,
    price_quarterly INTEGER,
    price_annual INTEGER,
    features TEXT NOT NULL,
    consultations_included INTEGER,
    messaging_unlimited INTEGER DEFAULT 0,
    nutrition_coaching INTEGER DEFAULT 0,
    priority_booking INTEGER DEFAULT 0,
    wearable_integration INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Patient subscriptions
CREATE TABLE IF NOT EXISTS patient_subscriptions (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    auto_renew INTEGER DEFAULT 1,
    payment_method TEXT,
    last_payment_date TEXT,
    next_payment_date TEXT,
    cancellation_date TEXT,
    cancellation_reason TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(id)
);

-- Consent audit log (DPDP compliance)
CREATE TABLE IF NOT EXISTS consent_audit_log (
    id TEXT PRIMARY KEY,
    patient_id TEXT NOT NULL,
    consent_type TEXT NOT NULL,
    consent_given INTEGER NOT NULL,
    consent_text TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    given_at TEXT DEFAULT (datetime('now')),
    withdrawn_at TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_doctors_specialty ON doctors(specialty);
CREATE INDEX IF NOT EXISTS idx_doctors_active ON doctors(is_active);
CREATE INDEX IF NOT EXISTS idx_weight_profiles_patient ON patient_weight_profiles(patient_id);
CREATE INDEX IF NOT EXISTS idx_weight_logs_patient ON weight_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_weight_logs_date ON weight_logs(logged_at);
CREATE INDEX IF NOT EXISTS idx_consultations_patient ON consultations(patient_id);
CREATE INDEX IF NOT EXISTS idx_consultations_doctor ON consultations(doctor_id);
CREATE INDEX IF NOT EXISTS idx_consultations_status ON consultations(status);
CREATE INDEX IF NOT EXISTS idx_consultations_scheduled ON consultations(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_prescriptions_patient ON prescriptions(patient_id);
CREATE INDEX IF NOT EXISTS idx_prescriptions_consultation ON prescriptions(consultation_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_orders_patient ON pharmacy_orders(patient_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_orders_status ON pharmacy_orders(order_status);
CREATE INDEX IF NOT EXISTS idx_patient_subs_patient ON patient_subscriptions(patient_id);
CREATE INDEX IF NOT EXISTS idx_consent_patient ON consent_audit_log(patient_id);
